apiVersion: v1
kind: ConfigMap
metadata:
  name: fastsmtp-config
  namespace: fastsmtp
data:
  FASTSMTP_API_HOST: "0.0.0.0"
  FASTSMTP_API_PORT: "8000"
  FASTSMTP_SMTP_HOST: "0.0.0.0"
  FASTSMTP_SMTP_PORT: "25"
  FASTSMTP_SMTP_TLS_PORT: "465"
  FASTSMTP_DATABASE_POOL_SIZE: "5"
  FASTSMTP_DATABASE_POOL_MAX_OVERFLOW: "10"
  FASTSMTP_WEBHOOK_MAX_RETRIES: "5"
  FASTSMTP_WEBHOOK_RETRY_DELAY: "60"
